name: Python Syntax Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  GeneralSyntaxCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Syntax Check with Python
        run: python -m compileall .

      - name: Lint with Flake8
        run: flake8 .

  CodeQualityCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety vulture radon pydocstyle black isort pyre-check

      - name: Security Check with Bandit
        run: bandit -r src

      - name: Dependency Security Check
        run: |
          if [ -f requirements.txt ]; then
            safety check -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping dependency security check."
          fi

      - name: Dead Code Detection with Vulture
        run: vulture .

      - name: Code Complexity Check with Radon
        run: radon cc . -a

      - name: Documentation Check with pydocstyle
        run: pydocstyle .

      - name: Format Python Code with Black
        run: black .

      - name: Check Python Code Formatting
        run: black --check .

      - name: Sort Imports with isort
        run: isort .

      - name: Check Import Sorting with isort
        run: isort --check-only .

  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi uvicorn jose passlib httpx

      - name: Run Unit Tests
        run: pytest tests/